networks:
  dev-terraflow:

services:
  terraflow:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    image: dev-terraflow
    container_name: dev-terraflow
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - TERRAFLOW_DATABASE_URL=postgresql://terraflow:terraflow@postgres:5432/terraflow
      - TERRAFLOW_SUPERUSER=terraflow
      - TERRAFLOW_SUPERUSER_PASSWORD=terraflow
      - TERRAFLOW_CONFIG_DIR=/var/lib/terraflow
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres
    networks:
      -  dev-terraflow


  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: terraflow
      POSTGRES_PASSWORD: terraflow
      POSTGRES_DB: terraflow
    ports:
      - "5432:5432"
    networks:
      -  dev-terraflow

