import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import Loading from "@/components/ui/loading";
import { useGetFilesV2 } from "@/controllers/API/queries/file-management";
import { useGetSandboxFiles } from "@/controllers/API/queries/file-management/use-get-sandbox-files";
import { useGetProjectFiles } from "@/controllers/API/queries/folders/use-get-project-files";
import type { ResolvedFileRef } from "@/types/appPage/widget";
import { buildProjectFileTree } from "./build-file-tree";
import { FileTree } from "./FileTree";

interface ProjectFilesTabProps {
  projectId: string;
  /** Only passed by the App page (see AppPage/components/widget-host.tsx) -- see FileTree's doc comment. */
  onOpenFile?: (ref: ResolvedFileRef, title: string) => void;
}

/**
 * Unified project-wide file browser, shown as a tree: files written by an
 * agent's sandboxed file tools (FileSystemTool/WordDocumentTool/
 * CommandExecutionTool), files generated by any flow in the project (v1
 * storage), and the user's own saved/uploaded files (v2 storage) -- see
 * build-file-tree.ts for how the three are grouped into folders. Shared
 * between the main Projects page (a permanent tab, see MainPage/pages/
 * homePage) and every flow's App page (a permanent first widget tab, see
 * AppPage/components/widget-host.tsx) -- same content either way, since it's
 * project-wide, not per-flow.
 */
const ProjectFilesTab = ({ projectId, onOpenFile }: ProjectFilesTabProps) => {
  const { t } = useTranslation();

  const { data: sandboxData, isLoading: sandboxLoading } = useGetSandboxFiles();
  const { data: projectFilesData, isLoading: projectFilesLoading } =
    useGetProjectFiles({ projectId });
  const { data: v2Files, isLoading: v2Loading } = useGetFilesV2();

  const isLoading = sandboxLoading || projectFilesLoading || v2Loading;
  const sandboxFiles = sandboxData?.files ?? [];
  const projectFiles = projectFilesData?.files ?? [];
  const myFiles = v2Files ?? [];

  const tree = useMemo(
    () =>
      buildProjectFileTree(sandboxFiles, projectFiles, myFiles, {
        sandbox: t("mainPage.filesFolderSandbox"),
        flowOutputs: t("mainPage.filesFolderFlowOutputs"),
        myFiles: t("mainPage.filesSourceMyFiles"),
      }),
    [sandboxFiles, projectFiles, myFiles, t],
  );

  if (isLoading) {
    return (
      <div className="flex h-full w-full items-center justify-center">
        <Loading />
      </div>
    );
  }

  if (tree.length === 0) {
    return (
      <div className="flex h-full w-full flex-col items-center justify-center gap-2 pt-24 text-center">
        <h3 className="text-2xl font-semibold">
          {t("mainPage.filesEmptyTitle")}
        </h3>
        <p className="text-lg text-secondary-foreground">
          {t("mainPage.filesEmptyDescription")}
        </p>
      </div>
    );
  }

  return (
    <div className="mt-4 h-full overflow-auto" data-testid="project-files-tab">
      <FileTree nodes={tree} onOpenFile={onOpenFile} />
    </div>
  );
};

export default ProjectFilesTab;
